import Head from 'next/head'
import Image from 'next/image'
import Banner from '../components/banner/Banner'
import Navbar from '../components/navbar/Navbar'
import Main from '../components/main'
import Footer from '../components/footer'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Readers Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <Banner />
        <Main />
        <Footer />
      </main>
        
    </div>
  )
}
